# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/wadey/gocovmerge"]

# We need runc at least 0.0.9 to get otherwise missing stubs for non-linux platforms.
# We need > 0.1.1 as it depends on uppercase Sirupsen/logrus.
[[override]]
  name = "github.com/opencontainers/runc"
  version = "v1.0.0-rc6"

[[override]]
  name = "github.com/docker/cli"
  revision = "3ddb3133f5b5a74dd4e3f721ced21f4d0b9651b6"

[[override]]
  name = "github.com/deislabs/duffle"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[[override]]
  name = "github.com/dgrijalva/jwt-go"
  revision = "v2.6.0"

[[override]]
  name = "github.com/docker/licensing"
  revision = "369e5301dc601b478021c0f588f5c3d04626d804"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[override]]
  name = "github.com/docker/go-metrics"
  revision = "d466d4f6fd960e01820085bd7e1a24426ee7ef18"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[override]]
  name = "github.com/docker/swarmkit"
  revision = "edd5641391926a50bc5f7040e20b7efc05003c26"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "v1.11.1"

[[override]]
  name = "k8s.io/api"
  revision = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.11.1"

# This is using a fork waiting for go-yaml/yaml#375 to be merged
# This PR allows to set a max decoded value, thus not being exposed to yaml bombs
[[override]]
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/simonferquel/yaml"
  revision="c86e64ed9581b7588e736f0c3e6ecc02cc22996e"

[[constraint]]
  name = "github.com/spf13/pflag"
  branch = "master"

[[constraint]]
  name = "github.com/wadey/gocovmerge"
  branch = "master"

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/docker/cli"
    non-go = false
