# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/wadey/gocovmerge"]

[[constraint]]
  name = "github.com/docker/cli"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[override]]
  name = "github.com/docker/go-metrics"
  revision = "d466d4f6fd960e01820085bd7e1a24426ee7ef18"

[[override]]
  name = "github.com/docker/docker"
  revision = "b711437bbd8596312c962d4189e9ad4d2108c2dc"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[override]]
  name = "github.com/docker/swarmkit"
  revision = "edd5641391926a50bc5f7040e20b7efc05003c26"

[[override]]
  name = "github.com/opencontainers/runc"
  revision = "ad0f5255060d36872be04de22f8731f38ef2d7b1"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "v1.11.1"

[[override]]
  name = "k8s.io/api"
  revision = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.11.1"

[[override]]
  name = "google.golang.org/grpc"
  revision = "v1.3.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  branch = "master"

[[constraint]]
  name = "github.com/wadey/gocovmerge"
  branch = "master"

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/docker/cli"
    non-go = false
